In [12]:
import pandas as pd
import json

pdf_file = '../../../datasets/chipnemo_os/open_dataset/academicpapers.jsonl'
jsonObj = pd.read_json(path_or_buf=pdf_file, lines=True)
jsonObj
# with open('/home/jvamaraju/dapt-data-curation/datasets/chipnemo_os/open_dataset/academicpapers.jsonl', 'r') as f:
#   academic_data = json.load(f)

,text,file,size,idx
0,DECC: Differential ECC for Read Performance Op...,/home/scratch.npinckney_research_1/llm_train/p...,21535,0
1,Optimizing Data Layout for Racetrack Memory in...,/home/scratch.npinckney_research_1/llm_train/p...,28453,0
2,Exploring Architectural Implications to Boost ...,/home/scratch.npinckney_research_1/llm_train/p...,28814,0
3,An Efficient Near-Bank Processing Architecture...,/home/scratch.npinckney_research_1/llm_train/p...,22787,0
4,PAALM: Power Density Aware Approximate Logarit...,/home/scratch.npinckney_research_1/llm_train/p...,24295,0
...,...,...,...,...
24005,"Part 1: What is OpenCLâ¢?\n\nJustin Hensley, ...",/home/scratch.npinckney_research_1/llm_train/p...,21309,0
24006,First Man: Redefining In-Camera FX\n\nPeter Fa...,/home/scratch.npinckney_research_1/llm_train/p...,835,0
24007,2020 IEEE International Conference on Quantum ...,/home/scratch.npinckney_research_1/llm_train/p...,34986,0
24008,1\n\nIntroduction\n\nMotion blur is an essenti...,/home/scratch.npinckney_research_1/llm_train/p...,32985,0
24009,A New Compact Analog VLSI Model for\nSpike Tim...,/home/scratch.npinckney_research_1/llm_train/p...,33397,0

In [9]:
github_files = '../../../datasets/chipnemo_os/open_dataset/github_v.jsonl'
jsonObj = pd.read_json(path_or_buf=github_files, lines=True)
with open('github_repos_opensource.jsonl', 'w') as fout:
    for item in pd.unique(jsonObj['repo_name']).tolist():
        fout.write(json.dumps(item)+"\n")
jsonObj[0:100]

,text,repo_name,ref,path,license,repository
0,/*\n *****************************************...,AngelTerrones/ADA,refs/heads/development,testbench/tb_ada_exception.v,mit,NaN
1,"module ptr(\n\tinput wire clk,\n\tinput wire r...",aap/pdp6,refs/heads/master,verilog/ptr.v,mit,NaN
2,/*\n * Copyright 2020 The SkyWater PDK Authors...,google/skywater-pdk-libs-sky130_fd_sc_lp,refs/heads/main,cells/dlxbp/sky130_fd_sc_lp__dlxbp.behavioral.v,apache-2.0,NaN
3,// @Harness: v2-parse\n// @Result: PASS\n\ncla...,Mah-D/VICE,refs/heads/master,test/parser/ptp_class03.v,mit,NaN
4,//-------------------------------------------...,olgirard/openmsp430,refs/heads/master,fpga/actel_m1a3pl_dev_kit/bench/verilog/DAC121...,bsd-3-clause,NaN
...,...,...,...,...,...,...
95,// DESCRIPTION: Verilator: Verilog Test module...,jeremybennett/verilator,refs/heads/bitsplit,test_regress/t/t_math_clog2.v,gpl-3.0,NaN
96,(** This file is very boring. It simply says t...,cobbal/ppl-ctx-equiv-coq,refs/heads/master,src/determinism.v,mit,NaN
97,/*\n * Copyright 2020 The SkyWater PDK Authors...,chipsalliance/Surelog,refs/heads/master,third_party/tests/Sky130Cell/cells/cells/sky13...,apache-2.0,NaN
98,/*********************************************...,olgirard/openmsp430,refs/heads/master,fpga/xilinx_avnet_lx9microbard/rtl/verilog/cor...,bsd-3-clause,NaN
99,"// Copyright 1986-2015 Xilinx, Inc. All Rights...",tnsrb93/G1_RealTimeDCTSteganography,refs/heads/master,src/ips/stream_encoder_ip_prj/stream_encoder_i...,gpl-3.0,NaN

In [10]:
verilog_files = '../../../datasets/chipnemo_os/open_dataset/verilog_entities_full.jsonl'
jsonObj = pd.read_json(path_or_buf=verilog_files, lines=True)
with open('wikiurls_opensource.jsonl', 'w') as fout:
    for item in pd.unique(jsonObj['url']).tolist():
        fout.write(json.dumps(item)+"\n")
jsonObj[0:100]

,text,title,id,url,language,source_id,adlr_id,split_id,kenlm_perplexity,kenlm_sp_perplexity
0,A memory rank is a set of DRAM chips connected...,Memory rank,25110379,https://en.wikipedia.org/wiki/Memory%20rank,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0002188052,task-dedup-split-0000,9.706903,307.976148
1,"In telecommunication, an isochronous signal is...",Isochronous signal,41293,https://en.wikipedia.org/wiki/Isochronous%20si...,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0002188835,task-dedup-split-0000,1031.630339,49.920145
2,"A73 or A-73 may refer to:\n\n Benoni Defense, ...",A73,3485038,https://en.wikipedia.org/wiki/A73,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0002189509,task-dedup-split-0000,2977.884811,87.217963
3,CCIX may refer to:\n\n The Roman number notati...,CCIX,56955079,https://en.wikipedia.org/wiki/CCIX,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0002192308,task-dedup-split-0000,2219.599831,414.962802
4,D.E.V.O.L.U.T.I.O.N. is the tenth studio album...,D.E.V.O.L.U.T.I.O.N.,17786091,https://en.wikipedia.org/wiki/D.E.V.O.L.U.T.I....,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0002196718,task-dedup-split-0000,1076.506636,150.890711
...,...,...,...,...,...,...,...,...,...,...
95,"The YM2608, a.k.a. OPNA, is a sound chip devel...",Yamaha YM2608,23379905,https://en.wikipedia.org/wiki/Yamaha%20YM2608,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0003335334,task-dedup-split-0000,8025.710561,218.324868
96,Number Assignment Module (NAM) - The NAM is th...,Number Assignment Module,1470131,https://en.wikipedia.org/wiki/Number%20Assignm...,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0003336003,task-dedup-split-0000,890.308607,427.705357
97,Parallel computing is a type of computation in...,Parallel computing,145162,https://en.wikipedia.org/wiki/Parallel%20compu...,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0003336280,task-dedup-split-0000,755.573327,144.885931
98,Operand forwarding (or data forwarding) is an ...,Operand forwarding,25199553,https://en.wikipedia.org/wiki/Operand%20forwar...,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0003337703,task-dedup-split-0000,1894.160766,336.907614
99,"HVM may refer to:\n\n HVM Racing, an auto raci...",HVM,13450393,https://en.wikipedia.org/wiki/HVM,en,enwiki-20230501-enwiki-20230501-pages-articles...,adlr-wikipedia-2023-0003338102,task-dedup-split-0000,777.422096,397.718707

In [36]:
import bs4
import requests


response = requests.get("https://en.wikipedia.org/wiki/Memory%20rank")

if response is not None:
    html = bs4.BeautifulSoup(response.content, "lxml")

    title = html.select("#firstHeading")[0].text
    paragraphs = html.find_all(["p","ul","li"])
#     for para in paragraphs:
#         print (para.text)

    # just grab the text up to contents as stated in question
    intro = '\n'.join([ para.text for para in paragraphs])
    print (intro.rstrip("\n"))
    print(title)

Main pageContentsCurrent eventsRandom articleAbout WikipediaContact usDonate

Main page
Contents
Current events
Random article
About Wikipedia
Contact us
Donate

HelpLearn to editCommunity portalRecent changesUpload file

Help
Learn to edit
Community portal
Recent changes
Upload file







Create account

Log in


Create account

Log in


 Create account Log in

 Create account
 Log in

ContributionsTalk

Contributions
Talk



(Top)





1Details







2Performance of multiple rank modules







3See also







4References



Toggle References subsection





4.1Bibliography









(Top)





1Details









2Performance of multiple rank modules









3See also









4References



Toggle References subsection





4.1Bibliography










4.1Bibliography








4.1Bibliography







Čeština

Čeština

ArticleTalk

Article
Talk



ReadEditView history

Read
Edit
View history

ReadEditView history

Read
Edit
View history

What links hereRelated changesUpload fileSpecial pagesPermanent linkPage informationCite this pageGet shortened URLDownload QR codeWikidata item

What links here
Related changes
Upload file
Special pages
Permanent link
Page information
Cite this page
Get shortened URL
Download QR code
Wikidata item

Download as PDFPrintable version

Download as PDF
Printable version
A memory rank is a set of DRAM chips connected to the same chip select, which are therefore accessed simultaneously. In practice all DRAM chips share all of the other command and control signals, and only the chip select pins for each rank are separate (the data pins are shared across ranks).[1]

The term rank was created and defined by JEDEC, the memory industry standards group. On a DDR, DDR2, or DDR3 memory module, each rank has a 64-bit-wide data bus (72 bits wide on DIMMs that support ECC). The number of physical DRAMs depends on their individual widths. For example, a rank of ×8 (8-bit wide) DRAMs would consist of eight physical chips (nine if ECC is supported), but a rank of ×4 (4-bit wide) DRAMs would consist of 16 physical chips (18, if ECC is supported). Multiple ranks can coexist on a single DIMM. Modern DIMMs can for example feature one rank (single rank), two ranks (dual rank), four ranks (quad rank), or eight ranks (octal rank).[citation needed]

There is only a little difference between a dual rank UDIMM and two single-rank UDIMMs in the same memory channel, other than that the DRAMs reside on different PCBs. The electrical connections between the memory controller and the DRAMs are almost identical (with the possible exception of which chip selects go to which ranks). Increasing the number of ranks per DIMM is mainly intended to increase the memory density per channel. Too many ranks in the channel can cause excessive loading and decrease the speed of the channel. Also some memory controllers have a maximum supported number of ranks. DRAM load on the command/address (CA) bus can be reduced by using registered memory.[citation needed]

Predating the term rank (sometimes also called row) is the use of single-sided and double-sided modules, especially with SIMMs. While most often the number of sides used to carry RAM chips corresponded to the number of ranks, sometimes they did not. This could lead to confusion and technical issues.[2][3]

There are several effects to consider regarding memory performance in multi-rank configurations:

Multi-rank modules allow several open DRAM pages (row) in each rank (typically eight pages per rank). This increases the possibility of getting a hit on an already open row address. The performance gain that can be achieved is highly dependent on the application and the memory controller's ability to take advantage of open pages.[citation needed]
Multi-rank modules have higher loading on the data bus (and on unbuffered DIMMs the CA bus as well). Therefore if more than dual rank DIMMs are connected in one channel, the speed might be reduced.[citation needed]
Subject to some limitations, ranks can be accessed independently, although not simultaneously as the data lines are still shared between ranks on a channel. For example, the controller can send write data to one rank while it awaits read data previously selected from another rank. While the write data is consumed from the data bus, the other rank could perform read-related operations such as the activation of a row or internal transfer of the data to the output drivers. Once the CA bus is free from noise from the previous read, the DRAM can drive out the read data. Controlling interleaved accesses like so is done by the memory controller.[citation needed]
There is a small performance reduction for multi-rank systems as they require some pipeline stalls between accessing different ranks. For two ranks on a single DIMM it might not even be required, but this parameter is often programmed independently of the rank location in the system (if on the same DIMM or different DIMMs). Nevertheless, this pipeline stall is negligible compared to the aforementioned effects.[citation needed]
Multi-rank modules allow several open DRAM pages (row) in each rank (typically eight pages per rank). This increases the possibility of getting a hit on an already open row address. The performance gain that can be achieved is highly dependent on the application and the memory controller's ability to take advantage of open pages.[citation needed]
Multi-rank modules have higher loading on the data bus (and on unbuffered DIMMs the CA bus as well). Therefore if more than dual rank DIMMs are connected in one channel, the speed might be reduced.[citation needed]
Subject to some limitations, ranks can be accessed independently, although not simultaneously as the data lines are still shared between ranks on a channel. For example, the controller can send write data to one rank while it awaits read data previously selected from another rank. While the write data is consumed from the data bus, the other rank could perform read-related operations such as the activation of a row or internal transfer of the data to the output drivers. Once the CA bus is free from noise from the previous read, the DRAM can drive out the read data. Controlling interleaved accesses like so is done by the memory controller.[citation needed]
There is a small performance reduction for multi-rank systems as they require some pipeline stalls between accessing different ranks. For two ranks on a single DIMM it might not even be required, but this parameter is often programmed independently of the rank location in the system (if on the same DIMM or different DIMMs). Nevertheless, this pipeline stall is negligible compared to the aforementioned effects.[citation needed]
Memory geometry
Memory geometry
^ "Definition of Rank". Retrieved 2017-09-25.

^ "An Overview of Memory". 2008-05-06. Retrieved 2017-08-09.

^ "Computer Memory Issues". Retrieved 2017-08-09.

Balasubramonian, Rajeev (May 2022). Innovations in the Memory System. Springer. ISBN 9783031017636.
Bruce, Jacob; Wang, David; Ng, Spencer (2008). Memory Systems: Cache, DRAM, Disk. Morgan Kaufmann Publishers. ISBN 978-0-12-379751-3.
Balasubramonian, Rajeev (May 2022). Innovations in the Memory System. Springer. ISBN 9783031017636.
Bruce, Jacob; Wang, David; Ng, Spencer (2008). Memory Systems: Cache, DRAM, Disk. Morgan Kaufmann Publishers. ISBN 978-0-12-379751-3.
Computer memory
Computer memory
Articles with short descriptionShort description is different from WikidataAll articles with unsourced statementsArticles with unsourced statements from November 2015Articles needing additional references from March 2022All articles needing additional references
Articles with short description
Short description is different from Wikidata
All articles with unsourced statements
Articles with unsourced statements from November 2015
Articles needing additional references from March 2022
All articles needing additional references

 This page was last edited on 18 September 2023, at 13:28 (UTC).
Text is available under the Creative Commons Attribution-ShareAlike License 4.0;
additional terms may apply. By using this site, you agree to the Terms of Use and Privacy Policy. Wikipedia® is a registered trademark of the Wikimedia Foundation, Inc., a non-profit organization.

 This page was last edited on 18 September 2023, at 13:28 (UTC).
Text is available under the Creative Commons Attribution-ShareAlike License 4.0;
additional terms may apply. By using this site, you agree to the Terms of Use and Privacy Policy. Wikipedia® is a registered trademark of the Wikimedia Foundation, Inc., a non-profit organization.

Privacy policy
About Wikipedia
Disclaimers
Contact Wikipedia
Code of Conduct
Developers
Statistics
Cookie statement
Mobile view

Privacy policy
About Wikipedia
Disclaimers
Contact Wikipedia
Code of Conduct
Developers
Statistics
Cookie statement
Mobile view









Toggle limited content width





Toggle limited content width
Memory rank

In [22]:
soup

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-0 vector-feature-appearance-disabled vector-feature-appearance-pinned-clientpref-0 vector-feature-night-mode-disabled skin-theme-clientpref-day vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Memory rank - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-0 vector-feature-appearance-disabled vector-feature-appearance-pinned-clientpref-0 vector-feature-night-mode-disabled skin-theme-clientpref-day vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":
["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"50a25feb-7424-4865-bddd-81e025acb606","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Memory_rank","wgTitle":"Memory rank","wgCurRevisionId":1175947759,"wgRevisionId":1175947759,"wgArticleId":25110379,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","All articles with unsourced statements","Articles with unsourced statements from November 2015","Articles needing additional references from March 2022","All articles needing additional references","Computer memory"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Memory_rank","wgRelevantArticleId":25110379,
"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviews":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":6,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":5000,"wgULSCurrentAutonym":"English","wgCentralAuthMobileDomain":false,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q6815753","wgCheckUserClientHintsHeadersJsApi":["architecture","bitness","brands","fullVersionList","mobile","model","platform","platformVersion"],
"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGEStructuredTaskRejectionReasonTextInputEnabled":false,"wgGELevelingUpEnabledForUser":false};RLSTATE={"skins.vector.user.styles":"ready","ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","skins.vector.user":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin",
"mmv.head","mmv.bootstrap.autostart","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.43.0-wmf.3" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1000" name="viewport"/>
<meta content="Memory rank - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/Memory_rank" media="only screen and (max-width: 720px)" rel="alternate"/>
<link href="/w/index.php?title=Memory_rank&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/opensearch_desc.php" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/Memory_rank" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="//login.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Memory_rank rootpage-Memory_rank skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark" role="navigation">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li><li class="mw-list-item" id="n-sitesupport"><a href="https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&amp;utm_medium=sidebar&amp;utm_campaign=C13_en.wikipedia.org&amp;uselang=en" title="Support us by donating to the Wikimedia Foundation"><span>Donate</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" id="" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide" role="navigation">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Memory+rank" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=Memory+rank" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=Memory+rank" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=Memory+rank" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">
		Pages for logged out editors <a aria-label="Learn more about editing" href="/wiki/Help:Introduction"><span>learn more</span></a>
</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="pt-anoncontribs"><a accesskey="y" href="/wiki/Special:MyContributions" title="A list of edits made from this IP address [y]"><span>Contributions</span></a></li><li class="mw-list-item" id="pt-anontalk"><a accesskey="n" href="/wiki/Special:MyTalk" title="Discussion about edits from this IP address [n]"><span>Talk</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">
<div class="notheme" id="siteNotice"><!-- CentralNotice --></div>
</div>
<div class="vector-column-start">
<div class="vector-main-menu-container">
<div id="mw-navigation">
<nav aria-label="Site" class="vector-main-menu-landmark" id="mw-panel" role="navigation">
<div class="vector-pinned-container" id="vector-main-menu-pinned-container">
</div>
</nav>
</div>
</div>
<div class="vector-sticky-pinned-container">
<nav aria-label="Contents" class="mw-table-of-contents-container vector-toc-landmark" data-event-name="ui.sidebar-toc" id="mw-panel-toc" role="navigation">
<div class="vector-pinned-container" id="vector-toc-pinned-container">
<div class="vector-toc vector-pinnable-element" id="vector-toc">
<div class="vector-pinnable-header vector-toc-pinnable-header vector-pinnable-header-pinned" data-feature-name="toc-pinned" data-pinnable-element-id="vector-toc">
<h2 class="vector-pinnable-header-label">Contents</h2>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-toc.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-toc.unpin">hide</button>
</div>
<ul class="vector-toc-contents" id="mw-panel-toc-list">
<li class="vector-toc-list-item vector-toc-level-1" id="toc-mw-content-text">
<a class="vector-toc-link" href="#">
<div class="vector-toc-text">(Top)</div>
</a>
</li>
<li class="vector-toc-list-item vector-toc-level-1 vector-toc-list-item-expanded" id="toc-Details">
<a class="vector-toc-link" href="#Details">
<div class="vector-toc-text">
<span class="vector-toc-numb">1</span>Details</div>
</a>
<ul class="vector-toc-list" id="toc-Details-sublist">
</ul>
</li>